### ISSUE TITLE
Installation with Carthage v0.14.0

### ISSUE THREAD

**Issue by Sina-KH** [rawrjustin/Bridge#1]
Hi, I get this error when I want to update my Carthage v0.14.0

**\* Fetching Bridge
**\* Checking out Bridge at "0.3.2"
**\* xcodebuild output can be found in /var/folders/5y/gz4k3lrj39lf90scpm_q8n480000gp/T/carthage-xcodebuild.Bz3rfZ.log
Failed to discover shared schemes in project BridgeTest.xcodeproj — either the project does not have any shared schemes, or xcodebuild timed out.

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/rawrjustin/Bridge/issues/new

**Comment by jzdhuang** [comment]
Hey @sina-kh, 
can you try master branch in your Cartfile?

`github "rawrjustin/Bridge" "master"`

There was a fix recently that may fix your issue. I'll release 0.3.3 off master if this fixes the issue.

**Comment by Sina-KH** [comment]
Thank you @rawrjustin 
Everything works as expected right now.

**Comment by sina-kh** [comment]
But now, what should I import to Endpoint be accessible? Bridge? Not working unfortunately!
I've added the framework to my target, but the Endpoint is not resolved yet.

**Comment by jzdhuang** [comment]
Let me know if you have any other issues, please close if everything works for you.

Thanks!
