### ISSUE TITLE
Passing params containing space character

### ISSUE THREAD

**Issue by Sina-KH** [rawrjustin/Bridge#2]
Hi.

I'm trying to pass ` `contained param name like`access token` and It doesn't work,
I think it's passing the name encoded?

Could you help me please?

**Comment by jzdhuang** [comment]
Is this a GET request where you are encoding the params in the URL?

**Comment by jzdhuang** [comment]
`pod "Bridge", :git => "https://github.com/rawrjustin/Bridge.git"`

just pushed a fix, let me know if it works

**Comment by Sina-KH** [comment]
I'm trying to post `access token`

Failed even with last push. :(

**Comment by jzdhuang** [comment]
1. Are you getting an error? 
2. are you using json bodies?
3. do you have an example request or scenario?

POST parameters are encoded via `NSJSONSerialization.dataWithJSONObject(parameters)` then attached to the `NSMutableURLRequest.HTTPBody`

I can't see anything that would break a POST request with a whitespace character in the key

**Comment by Sina-KH** [comment]
1. Nope! Just the parameter not being send correctly and I get that parameter is missing. But I can get response in postman!
2. Where? Just the response is JSON.
3. Just test this please :

http://app.omidanalyzer.com/application/api/v2/signal/behavior

and pass `signal_id` and `access token` !! In postman you will get wrong token error but in Bridge you will get that access token is not being passed!

Thank You.

**Comment by jzdhuang** [comment]
thanks for the detailed response - it'll help me in debugging, i'll look into it now

**Comment by jzdhuang** [comment]
@sina-kh  here's the curl command I'm using (just paste into your terminal if you're using linux/osx)
`curl -H "Content-Type: application/json" -X POST -d '{"signal_id": 123,"access token":"xyz"}' http://app.omidanalyzer.com/application/api/v2/signal/behavior`

Trying that api endpoint in both curl and postman doesn't seem to work for me. I'm getting this error

```
{
  "error":"invalid_request",
  "error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."
}
```

Can you tell me what I'm doing wrong here? Thanks

**Comment by Sina-KH** [comment]
This is the working curl for the web service:

curl -X POST  -H "Content-Type: multipart/form-data;" -F "access token=xyz" -F "signal_id=139" "http://app.omidanalyzer.com/application/api/v2/signal/behavior"

**Comment by jzdhuang** [comment]
Ah, thanks for the clarification Bridge currently only supports `application/json`
We're currently working on multipart/form-data posts but it's not finished yet, sorry about that.

you can track our progress here: 
https://github.com/rawrjustin/Bridge/issues/3

In the meantime, I would recommend
https://github.com/Alamofire/Alamofire

**Comment by Sina-KH** [comment]
OK, thanks bro. Good Luck ;)

**Comment by jzdhuang** [comment]
@sina-kh thank you for helping out/using Bridge! :smile:
